# Generated by Django 5.1 on 2024-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/product_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/vendor_logos/'),
        ),
    ]
