# Generated by Django 5.1 on 2024-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_product_product_image_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='staticfiles/product_images'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/vendor_logos/'),
        ),
    ]
