# Generated by Django 5.1 on 2024-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
