# Generated by Django 5.1 on 2024-09-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_user_password_alter_user_username_orderproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_bought',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_searched',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_bought_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_searched_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
