# Generated by Django 5.1 on 2024-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
